### ISSUE TITLE
Not compatible with ckeditor5 v11

### ISSUE THREAD

**Issue by joachimdoerr** [wwalc/ckeditor5-emoji#5]
Console log:
```
plugincollection-plugin-name-conflict: Two plugins with the same name were loaded. Read more: https://docs.ckeditor.com/ckeditor5/latest/framework/guides/support/error-codes.html#error-plugincollection-plugin-name-conflict
Object
plugin1: function()
plugin2: function()
pluginName: "ContextualBalloon"
Object Prototyp
```
I try to use the emoji plugin for the ckeditor5 v11.

I lost the style for the toolbar and the dropdown menus like alignment are defect.

![bildschirmfoto 2018-07-26 um 16 39 00](https://user-images.githubusercontent.com/1191549/43269215-afedc854-90f2-11e8-825d-9f8d16ed730b.png)
![bildschirmfoto 2018-07-26 um 16 39 30](https://user-images.githubusercontent.com/1191549/43269223-b37e2b30-90f2-11e8-9ec8-23c6f60224cf.png)

**Comment by wwalc** [comment]
I just published a new version: 11.0.0, could you try again? If it still does not work, clone the CKEditor 5 build again and add the plugin.

Make sure to follow this instruction: https://docs.ckeditor.com/ckeditor5/latest/builds/guides/development/custom-builds.html

**Comment by joachimdoerr** [comment]
I try it with your new version but the result is the same no changes.

**Comment by wwalc** [comment]
Try again with version 11.0.2 of `@wwalc/ckeditor5-emoji`? This version will work on 100% with any CKEditor 10.0.0+. I tested it while checking https://github.com/ckeditor/ckeditor5/issues/1061#issuecomment-408398707
If your build still does not work with it then it means that the problem is in a different place.

`rm -rf node_modules`, cleanup package.json from 3rd party plugins, run `npm install` and then `npm install --save @wwalc/ckeditor5-emoji`

**Comment by joachimdoerr** [comment]
Thanks now it works fine.
